development:
  adapter: mysql2
  database: ottomatic_development
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: ottomatic_production
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: ottomatic_test
  username: root
  password:
  host: localhost
  encoding: utf8
